spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/project
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: false