spring:
  datasource:
    username: sql11685277
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11685277
    password: KyuRdLVwtZ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: false